spring:
    appliation:
      name: eurekaSrv

server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false   # 通过eureka.client.registerWithEureka：false和fetchRegistry：false来表明自己是一个eureka server.
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      ## defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/